[2025-06-20T02:16:02.712+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_quotes_to_csv2.crawl_to_csv2 scheduled__2025-06-20T02:15:00+00:00 [queued]>
[2025-06-20T02:16:02.715+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_quotes_to_csv2.crawl_to_csv2 scheduled__2025-06-20T02:15:00+00:00 [queued]>
[2025-06-20T02:16:02.715+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-20T02:16:02.724+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): crawl_to_csv2> on 2025-06-20 02:15:00+00:00
[2025-06-20T02:16:02.726+0000] {standard_task_runner.py:60} INFO - Started process 9860 to run task
[2025-06-20T02:16:02.728+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'crawl_quotes_to_csv2', 'crawl_to_csv2', 'scheduled__2025-06-20T02:15:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/web_crawling_to_csv.py', '--cfg-path', '/tmp/tmp3bevxhuc']
[2025-06-20T02:16:02.730+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask crawl_to_csv2
[2025-06-20T02:16:02.755+0000] {task_command.py:423} INFO - Running <TaskInstance: crawl_quotes_to_csv2.crawl_to_csv2 scheduled__2025-06-20T02:15:00+00:00 [running]> on host kmh-server
[2025-06-20T02:16:02.792+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crawl_quotes_to_csv2' AIRFLOW_CTX_TASK_ID='crawl_to_csv2' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T02:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-20T02:15:00+00:00'
[2025-06-20T02:16:03.575+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kmh/de_basic/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 428, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmh/de_basic/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmh/de_basic/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmh/de_basic/airflow/dags/web_crawling_to_csv.py", line 42, in crawl_to_csv
    utc_dt = datetime.strptime(execution_time, "%Y-%m-%dT%H:%M:%S")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmh/.local/share/uv/python/cpython-3.11.12-linux-x86_64-gnu/lib/python3.11/_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmh/.local/share/uv/python/cpython-3.11.12-linux-x86_64-gnu/lib/python3.11/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2025-06-20T02:16:03.586+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=crawl_quotes_to_csv2, task_id=crawl_to_csv2, execution_date=20250620T021500, start_date=20250620T021602, end_date=20250620T021603
[2025-06-20T02:16:03.600+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task crawl_to_csv2 (unconverted data remains: +00:00; 9860)
[2025-06-20T02:16:03.638+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-20T02:16:03.646+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
